# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from class_select import ClassSelect
from promptDialog import Ui_Dialog
from updatealert import UpdateAlert
from updateForm import UpdateForm


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 608)
        MainWindow.setStyleSheet("background-image : url(./res/dark theme.jpeg);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.home_frame = QtWidgets.QFrame(self.centralwidget)
        self.home_frame.setGeometry(QtCore.QRect(70, 50, 831, 421))
        self.home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_frame.setObjectName("home_frame")
        self.home_frame.setStyleSheet("background-image : url(./res/dark.jpeg);")

        self.update_button = QtWidgets.QPushButton(self.home_frame)
        self.update_button.setGeometry(QtCore.QRect(60, 150, 181, 101))
        self.update_button.setObjectName("update_button")
        self.update_button.setText("")
        self.update_button.setStyleSheet("border-image : url(./res/Upload Defaults.png) 0 0 0 0 stretch "
                                         "stretch;border : 2px solid blue")
        self.update_button.clicked.connect(self.update_on_clicked)

        self.allotment_button = QtWidgets.QPushButton(self.home_frame)
        self.allotment_button.setGeometry(QtCore.QRect(530, 150, 181, 101))
        self.allotment_button.setObjectName("allotment_button")
        self.allotment_button.setText("Allotment")
        self.allotment_button.setStyleSheet("border-image : url(./res/allotment.png) 0 0 0 0 stretch "
                                            "stretch;border : 2px solid blue")

        self.allotment_button.clicked.connect(self.allot_on_clicked)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def update_on_clicked(self):
        ua = UpdateAlert(self.centralwidget)
        if ua.is_ok:
            uf = UpdateForm(self.centralwidget)
            if uf.is_ok:
                self.label = QtWidgets.QLabel(self.home_frame)
                self.label.setGeometry(QtCore.QRect(130, 100, 201, 17))
                self.label.setStyleSheet("font: 75 11pt \"Tibetan Machine Uni\" bold;\n"
                                         "color: rgb(78, 154, 6);")
                self.label.setObjectName("label")
                self.label.setText("File Updated Successfully")
                self.label.show()



    def allot_on_clicked(self):
        self.home_frame.deleteLater()
        Ui_Dialog(self.centralwidget)
        # ClassSelect(self.centralwidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
