# -*- coding: utf-8 -*-

# self.Form implementation generated from reading ui file 'updateself.Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QFileDialog
from readDatabase import get_classes, check_halls


def vaidate():
    pass


class UpdateForm(QDialog):
    def __init__(self, centralWidget):
        super().__init__()
        self.centralWidget = centralWidget
        self.Form = QtWidgets.QFrame(self)
        self.setupUi()
        self.is_ok = False
        self.exec()

    def setupUi(self):
        self.Form.setObjectName("self.Form")
        self.Form.resize(687, 442)
        self.label = QtWidgets.QLabel(self.Form)
        self.label.setGeometry(QtCore.QRect(70, 60, 451, 20))
        self.label.setStyleSheet("font: 75 11pt \"Tibetan Machine Uni\";\n"
                                 "color: rgb(204, 0, 0);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 180, 151, 81))
        self.pushButton.setStyleSheet("font: 75 11pt \"Tibetan Machine Uni\";\n"
                                      "background-color: rgb(85, 87, 83);\n"
                                      "color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.Form)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 180, 161, 81))
        self.pushButton_2.setStyleSheet("font: 75 11pt \"Tibetan Machine Uni\";\n"
                                        "background-color: rgb(85, 87, 83);\n"
                                        "color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Form)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 330, 89, 25))
        self.pushButton_3.hide()
        self.pushButton_3.setStyleSheet("font: 75 11pt \"Tibetan Machine Uni\";\n"
                                        "background-color: rgb(85, 87, 83);\n"
                                        "color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Form)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 330, 89, 25))
        self.pushButton_4.setStyleSheet("font: 75 11pt \"Tibetan Machine Uni\";\n"
                                        "background-color: rgb(85, 87, 83);\n"
                                        "color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_4.clicked.connect(self.cancel)

        self.pushButton_3.clicked.connect(self.ok)
        self.pushButton.clicked.connect(self.student_database)
        self.pushButton_2.clicked.connect(self.exam_halls)

        self.retranslateUi(self.Form)
        QtCore.QMetaObject.connectSlotsByName(self.Form)

    def ok(self):
        pass

    def exam_halls(self):
        directory = QFileDialog.getOpenFileName()
        directory = directory[0]
        print(directory)
        temp = check_halls(directory)
        if "message" not in temp and len(temp) > 1:
            self.is_ok = True
            print("file Accepted")
            self.close()

        else:
            print(temp)

    def student_database(self):
        directory = QFileDialog.getOpenFileName()
        directory = directory[0]
        print(directory)
        temp = get_classes(directory)
        if "message" not in temp and len(temp) > 1:
            self.is_ok = True
            print("file Accepted")
            self.close()

        else:
            print(temp)

    def cancel(self):
        self.is_ok = False
        self.deleteLater()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.Form.setWindowTitle(_translate("self.Form", "self.Form"))
        self.label.setText(_translate("self.Form", "Once you update the file, the old file will be deleted!!!"))
        self.pushButton.setText(_translate("self.Form", "Student Database"))
        self.pushButton_2.setText(_translate("self.Form", "Default Exam Halls"))
        self.pushButton_3.setText(_translate("self.Form", "Ok"))
        self.pushButton_4.setText(_translate("self.Form", "Cancel"))
